import type { SourceCandidate } from "./relevance-score.ts";

const INFORMATION_PARADOX_SOURCES: SourceCandidate[] = [
  {
    id: "foundational-hawking-particle-creation-1975",
    title: "Particle Creation by Black Holes",
    abstract: "Hawking derives black-hole particle emission with an exactly thermal spectrum in the idealized semiclassical treatment, establishing the physical setup behind black-hole evaporation and the information problem.",
    authors: ["Stephen W. Hawking"],
    year: 1975,
    provider: "Springer",
    source: "Communications in Mathematical Physics",
    url: "https://doi.org/10.1007/BF02345020",
    doi: "10.1007/BF02345020",
    sourceClass: "foundational",
    foundationalPriority: 1,
    citationLabel: "[Hawking 1975]",
    relevanceReason: "Established the semiclassical thermal-radiation result that creates the physical setup for the information paradox.",
  },
  {
    id: "foundational-hawking-predictability-1976",
    title: "Breakdown of Predictability in Gravitational Collapse",
    abstract: "Hawking argues that complete black-hole evaporation can map an initially pure quantum state to thermal mixed radiation, formulating the information-loss challenge to ordinary unitary quantum evolution.",
    authors: ["Stephen W. Hawking"],
    year: 1976,
    provider: "APS",
    source: "Physical Review D",
    url: "https://doi.org/10.1103/PhysRevD.14.2460",
    doi: "10.1103/PhysRevD.14.2460",
    sourceClass: "foundational",
    benchmarkCategory: "information-loss",
    foundationalPriority: 2,
    citationLabel: "[Hawking 1976]",
    relevanceReason: "Formulated the pure-to-mixed evolution and loss-of-predictability version of the paradox.",
  },
  {
    id: "foundational-page-radiation-1993",
    title: "Information in Black Hole Radiation",
    abstract: "Page analyzes unitary black-hole evaporation and the entropy of emitted radiation, motivating the Page curve, the Page time, and late-time information recovery through radiation correlations.",
    authors: ["Don N. Page"],
    year: 1993,
    provider: "arXiv",
    source: "Physical Review Letters",
    url: "https://arxiv.org/abs/hep-th/9306083",
    doi: "10.1103/PhysRevLett.71.3743",
    arxivId: "hep-th/9306083",
    sourceClass: "foundational",
    benchmarkCategory: "page-curve",
    foundationalPriority: 3,
    citationLabel: "[Page 1993]",
    relevanceReason: "Provides the foundational unitary-evaporation argument behind the Page curve and information-recovery timescale.",
  },
  {
    id: "foundational-complementarity-1993",
    title: "The Stretched Horizon and Black Hole Complementarity",
    abstract: "Susskind, Thorlacius, and Uglum formulate black-hole complementarity: distant and infalling descriptions can preserve quantum mechanics without any one observer witnessing duplicated information.",
    authors: ["Leonard Susskind", "Larus Thorlacius", "John Uglum"],
    year: 1993,
    provider: "arXiv",
    source: "Physical Review D",
    url: "https://arxiv.org/abs/hep-th/9306069",
    doi: "10.1103/PhysRevD.48.3743",
    arxivId: "hep-th/9306069",
    sourceClass: "landmark-development",
    benchmarkCategory: "complementarity-firewall",
    foundationalPriority: 4,
    citationLabel: "[Susskind et al. 1993]",
    relevanceReason: "Introduced the principal complementarity framework for reconciling unitary exterior evolution with a smooth infalling experience.",
  },
  {
    id: "foundational-maldacena-ads-cft-1997",
    title: "The Large N Limit of Superconformal Field Theories and Supergravity",
    abstract: "Maldacena proposes the AdS/CFT correspondence, relating a gravitational theory in anti-de Sitter space to a nongravitational conformal field theory with unitary quantum evolution.",
    authors: ["Juan M. Maldacena"],
    year: 1997,
    provider: "arXiv",
    source: "Advances in Theoretical and Mathematical Physics",
    url: "https://arxiv.org/abs/hep-th/9711200",
    arxivId: "hep-th/9711200",
    sourceClass: "landmark-development",
    benchmarkCategory: "holography",
    foundationalPriority: 5,
    citationLabel: "[Maldacena 1997]",
    relevanceReason: "Underpins the strongest holographic evidence that a complete quantum-gravity description of black holes is unitary.",
  },
  {
    id: "modern-amps-firewall-2012",
    title: "Black Holes: Complementarity or Firewalls?",
    abstract: "Almheiri, Marolf, Polchinski, and Sully show a conflict among pure Hawking radiation, low-energy effective field theory outside the horizon, and a smooth horizon, motivating the firewall proposal.",
    authors: ["Ahmed Almheiri", "Donald Marolf", "Joseph Polchinski", "James Sully"],
    year: 2012,
    provider: "arXiv",
    source: "Journal of High Energy Physics",
    url: "https://arxiv.org/abs/1207.3123",
    doi: "10.1007/JHEP02(2013)062",
    arxivId: "1207.3123",
    sourceClass: "landmark-development",
    benchmarkCategory: "complementarity-firewall",
    foundationalPriority: 6,
    citationLabel: "[Almheiri et al. 2012]",
    relevanceReason: "Defines the AMPS entanglement conflict and the disputed firewall response to it.",
  },
  {
    id: "modern-island-page-curve-2019",
    title: "The Page Curve of Hawking Radiation from Semiclassical Geometry",
    abstract: "Almheiri, Mahajan, Maldacena, and Zhao use quantum extremal surfaces and an island prescription in a controlled holographic model to reproduce the unitary Page curve for Hawking radiation.",
    authors: ["Ahmed Almheiri", "Raghu Mahajan", "Juan Maldacena", "Ying Zhao"],
    year: 2019,
    provider: "arXiv",
    source: "Journal of High Energy Physics",
    url: "https://arxiv.org/abs/1908.10996",
    doi: "10.1007/JHEP03(2020)149",
    arxivId: "1908.10996",
    sourceClass: "modern-resolution",
    benchmarkCategory: "island-replica",
    foundationalPriority: 7,
    citationLabel: "[Almheiri et al. 2019]",
    relevanceReason: "Shows how the island formula and quantum extremal surfaces reproduce the Page curve in a controlled semiclassical holographic setting.",
  },
  {
    id: "modern-replica-wormholes-2019",
    title: "Replica Wormholes and the Black Hole Interior",
    abstract: "Penington, Shenker, Stanford, and Yang derive Page-curve behavior from replica-wormhole saddle points and connect the result to entanglement-wedge reconstruction in controlled gravity models.",
    authors: ["Geoffrey Penington", "Stephen H. Shenker", "Douglas Stanford", "Zhenbin Yang"],
    year: 2019,
    provider: "arXiv",
    source: "Journal of High Energy Physics",
    url: "https://arxiv.org/abs/1911.11977",
    arxivId: "1911.11977",
    sourceClass: "modern-resolution",
    benchmarkCategory: "island-replica",
    foundationalPriority: 8,
    citationLabel: "[Penington et al. 2019]",
    relevanceReason: "Provides a gravitational path-integral derivation of replica-wormhole contributions associated with the Page transition.",
  },
];

export function getVerifiedResearchCatalogue(): SourceCandidate[] {
  return INFORMATION_PARADOX_SOURCES.map((source) => ({
    ...source,
    authors: source.authors ? [...source.authors] : undefined,
    concepts: source.concepts ? [...source.concepts] : undefined,
    keywords: source.keywords ? [...source.keywords] : undefined,
  }));
}

export function getFoundationalResearchSources(query: string): SourceCandidate[] {
  const normalized = query.toLowerCase().replace(/-/g, " ").replace(/\s+/g, " ");
  const matchesInformationParadox = [
    "black hole",
    "event horizon",
    "hawking radiation",
    "page curve",
    "page time",
    "information loss",
    "information recovery",
    "unitarity",
    "replica wormhole",
    "island formula",
  ].some((term) => normalized.includes(term));

  return matchesInformationParadox ? getVerifiedResearchCatalogue() : [];
}
